### ISSUE TITLE
Project tabs need URL parameter

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/Axon#10]

**Comment by GrantPerkins** [comment]
@AustinShalit what is the URL parameter?

**Comment by AustinShalit** [comment]
URL parameters are either in path (like what we use to go to project pages or dataset pages) or as GET params (after a `#`). They are useful because when you hard refresh a page you are brought back to where you left off instead of needing to navigate again.

This is actually not an issue anymore because we do not use tabs on the project page.
