### ISSUE TITLE
Testing in Firefox crashes Axon

### ISSUE THREAD

**Issue by GrantPerkins** [wpilibsuite/Axon#108]

**Comment by AustinShalit** [comment]
What were you doing? I cannot reproduce on macOS with Firefox 84.0.2.

**Comment by GrantPerkins** [comment]
Clicking the "test" button on an exported model. Yoni had the same issue. @phonymacoroni

**Comment by phonymacoroni** [comment]
@AustinShalit I am also on macOS 84.0.2

Issue occurred once a video had been selected I believe.

This does not occur in Safari

**Comment by GrantPerkins** [comment]
Resolved by one of nestor's recent commits.
