### ISSUE TITLE
Not selecting a dataset crashes app

### ISSUE THREAD

**Issue by GrantPerkins** [wpilibsuite/Axon#109]
should ensure all data is valid in parameters before training starts.

**Comment by AustinShalit** [comment]
This probably requires 2 changes. One change to the backend to make sure the application does not crash and one change to the UI to prevent the user from starting without a dataset selection registered by the backend.

**Comment by phonymacoroni** [comment]
Here is the log from attempting to run with no dataset selected.

https://pastebin.com/y7Z8s4PU

Once that is complete, no crashing occurs for me and the remainder of the functions of the application

**Comment by phonymacoroni** [comment]
Previous paste was run in `dev`

Paste: https://pastebin.com/66AyENWb

Run with `dockerdev`

Both cases do allow app to continue functions

**Comment by GrantPerkins** [comment]
Hmm. It crashed on the new mac. Anyway, we should not be able to run a training job without a dataset selected.
