### ISSUE TITLE
Exporting multiple checkpoints at the same time crashes axon

### ISSUE THREAD

**Issue by phonymacoroni** [wpilibsuite/Axon#157]
https://pastebin.com/WCcyQiMq

**Comment by GrantPerkins** [comment]
What are steps to reproduce?

**Comment by phonymacoroni** [comment]
Crash occured after training

-Select final checkpoint and click export
-Seconds after select another checkpoint and click export
-Axon crashes

**Comment by AustinShalit** [comment]
Looks like we need to include more unique information in the container name. This should probably be accompanied by more usage of container tags.
