### ISSUE TITLE
Create - multiword class name support

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/Axon#228]
Multiword class names currently do not work and it fails without alerting the user.

**Comment by GrantPerkins** [comment]
Is this the same issue with "remote control"? Or is this not OpenImages?

**Comment by GrantPerkins** [comment]
What were you trying to do when Axon failed?

**Comment by AustinShalit** [comment]
Same as remote control/open images.

**Comment by GrantPerkins** [comment]
Not able to recreate. Screenshot this occuring in master branch?

**Comment by AustinShalit** [comment]
Ah it is fixed!
